

PRINT @CLIENTE
PRINT @IDADE
PRINT @DATANASCIMENTO	
PRINT @CUSTO

/* exercício 1 T-SQL*/
DECLARE @CLIENTE VARCHAR(10) = 'João'
DECLARE @IDADE INT = 10
DECLARE @DATANASCIMENTO DATE = '20070110'
DECLARE @CUSTO FLOAT = 10.23

PRINT @CLIENTE
PRINT @IDADE
PRINT @DATANASCIMENTO	
PRINT @CUSTO

/* exercício 2 T-SQL*/
DECLARE @NUMNOTAS INT
SELECT @NUMNOTAS = COUNT(*) FROM [NOTAS FISCAIS] 
WHERE [DATA] = '20170101' 
PRINT @NUMNOTAS

/* exercício 3 T-SQL*/
IF OBJECT_ID('TABLE_TESTE','U') IS NOT NULL
BEGIN
	DROP TABLE TABLE_TESTE
END
ELSE
BEGIN
	CREATE TABLE TABLE_TESTE (ID VARCHAR(10))
END




